name: CI

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Make
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          script: |
            docker stop pkchub
            docker rm pkchub
            rm -r ./pkchub/
            git clone https://github.com/yuriy-matsay/pkchub.git
            cd ./pkchub/
            docker build . -t pkchubimage:$(echo $GITHUB_SHA | head -c7)
           
            
            
